# Generated by Django 5.1.4 on 2024-12-06 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Available", "Available"), ("Issued", "Issued")],
                        default="Available",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
