# Generated by Django 5.1.4 on 2024-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BookShelf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                default="book_covers/default_cover.png",
                null=True,
                upload_to="book_covers/",
            ),
        ),
    ]
