# Generated by Django 5.1.4 on 2024-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BookShelf", "0003_alter_book_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
